title: Emma Collins # your name (or website title) here
logo: "/images/profilepic.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Test One
  <br><br>
  Test Two 
  <br><br>
  <a href="https://www.linkedin.com/in/emma-m-collins/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

