title: Emma M Collins # your name (or website title) here
logo: "/images/profile_pic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Recent MS, Satistics graduate looking for a junior data scientist position at a data-driven company in the Denver Metro area.
  <br><br>
  When not data-crunching, you can find me paddle boarding or baking.
  <br><br>
  <a href="https://www.linkedin.com/in/emma-m-collins/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/Emma-M-Collins">View My GitHub Profile</a>
  
theme: jekyll-theme-minimal

